version: "3.9"
services:
  web:
    build: .
    ports:
      - "5005:5005"
    environment:
      FLASK_DEBUG: "true"
      DB_HOST: "postgres"
    hostname: "web"

  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "mysecretpassword"