version: "3.9"
services:
  web:
    build: .
    command: python3 app.py
    ports:
      - "5005:5005"
    environment:
      FLASK_DEBUG: "true"
      DB_HOST: "postgres"
      MONGO_HOST: "mongodb"
    hostname: "web"

  celery_worker:
    build: .
    command: celery -A celery_worker worker --loglevel=INFO --purge --pool=solo
    environment:
      RABBIT_HOST: "rabbit_host"
      DB_HOST: "postgres"
    hostname: "celery_worker"

  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "mysecretpassword"

  mongo:
    image: mongo
    restart: always
    hostname: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: crm_db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/

  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    ports:
        - "5672:5672"
        - "15672:15672"
    hostname: "rabbit_host"