"""empty message

Revision ID: 558ccc954f08
Revises: 7714bb3919a5
Create Date: 2023-03-01 23:41:01.190538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '558ccc954f08'
down_revision = '7714bb3919a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_credentials', sa.Column('pop_port', sa.Integer(), nullable=True))
    op.add_column('email_credentials', sa.Column('smtp_port', sa.Integer(), nullable=True))
    op.add_column('email_credentials', sa.Column('imap_server', sa.String(length=50), nullable=True))
    op.add_column('email_credentials', sa.Column('imap_port', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_credentials', 'imap_port')
    op.drop_column('email_credentials', 'imap_server')
    op.drop_column('email_credentials', 'smtp_port')
    op.drop_column('email_credentials', 'pop_port')
    # ### end Alembic commands ###
