"""empty message

Revision ID: 7714bb3919a5
Revises: 1d659e13c06b
Create Date: 2023-02-26 00:20:01.559416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7714bb3919a5'
down_revision = '1d659e13c06b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_credentials', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('email_credentials', 'pop_server',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('email_credentials', 'smtp_server',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_credentials', 'smtp_server',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('email_credentials', 'pop_server',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('email_credentials', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
